import React, { useState, useEffect, useMemo, useRef } from 'react';
import {
  QrCode,
  Save,
  ShieldCheck,
  Check,
  Smartphone,
  Copy,
  CheckCircle2,
  RefreshCw,
  Upload,
  Image as ImageIcon,
  Trash2,
  AlertCircle,
  Sparkles,
  ToggleLeft,
  ToggleRight,
  Info,
  RotateCcw,
  Building2,
  FileText,
  IndianRupee,
} from 'lucide-react';
import { useStore } from '../../context/StoreContext';
import { PaymentSettings } from '../../types';
import { generateUPILink, getQRCodeImageUrl, cleanAndSanitizeUPIId, isValidUPIIdFormat } from '../../utils/qrCode';

export const PaymentSettingsView: React.FC = () => {
  const { paymentSettings, updatePaymentSettings } = useStore();

  // Local Form State
  const [upiId, setUpiId] = useState(paymentSettings.upiId || 'marudharfashion@upi');
  const [merchantName, setMerchantName] = useState(paymentSettings.merchantName || 'Marudhar Fashion Point');
  const [paymentEnabled, setPaymentEnabled] = useState(paymentSettings.paymentEnabled !== false);
  const [paymentInstructions, setPaymentInstructions] = useState(
    paymentSettings.paymentInstructions ||
      'Scan the QR code using Google Pay, PhonePe, Paytm, or BHIM UPI app. Enter transaction ID after completing payment.'
  );
  const [minOrderAmount, setMinOrderAmount] = useState<number>(paymentSettings.minOrderAmount ?? 1);
  const [maxOrderAmount, setMaxOrderAmount] = useState<number>(paymentSettings.maxOrderAmount ?? 0);

  // QR Mode: 'AUTO' or 'CUSTOM'
  const [qrMode, setQrMode] = useState<'AUTO' | 'CUSTOM'>(
    paymentSettings.qrCodeCustomImage ? 'CUSTOM' : 'AUTO'
  );
  const [customQrImage, setCustomQrImage] = useState<string>(paymentSettings.qrCodeCustomImage || '');

  // UI status states
  const [isSaving, setIsSaving] = useState(false);
  const [saveStatus, setSaveStatus] = useState<'IDLE' | 'SAVING' | 'SUCCESS' | 'ERROR'>('IDLE');
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [copiedUPI, setCopiedUPI] = useState(false);
  const fileInputRef = useRef<HTMLInputElement | null>(null);

  // Sync form state when remote Firestore paymentSettings changes (if not actively editing)
  useEffect(() => {
    if (saveStatus === 'SAVING') return;
    setUpiId(paymentSettings.upiId || 'marudharfashion@upi');
    setMerchantName(paymentSettings.merchantName || 'Marudhar Fashion Point');
    setPaymentEnabled(paymentSettings.paymentEnabled !== false);
    setPaymentInstructions(
      paymentSettings.paymentInstructions ||
        'Scan the QR code using Google Pay, PhonePe, Paytm, or BHIM UPI app. Enter transaction ID after completing payment.'
    );
    setMinOrderAmount(paymentSettings.minOrderAmount ?? 1);
    setMaxOrderAmount(paymentSettings.maxOrderAmount ?? 0);
    if (paymentSettings.qrCodeCustomImage) {
      setCustomQrImage(paymentSettings.qrCodeCustomImage);
      setQrMode('CUSTOM');
    }
  }, [paymentSettings]);

  // VPA Validation Regex
  const isVpaValid = useMemo(() => {
    return isValidUPIIdFormat(upiId);
  }, [upiId]);

  // Auto-generated dynamic UPI link & QR image URL
  const autoGeneratedUpiLink = useMemo(() => {
    return generateUPILink(
      cleanAndSanitizeUPIId(upiId) || 'marudharfashion@upi',
      merchantName || 'Marudhar Fashion Point',
      2499,
      'MFP1025'
    );
  }, [upiId, merchantName]);

  const autoGeneratedQrUrl = useMemo(() => {
    return getQRCodeImageUrl(autoGeneratedUpiLink, 300);
  }, [autoGeneratedUpiLink]);

  // Effective QR Code image URL to use
  const effectiveQrImage = qrMode === 'CUSTOM' && customQrImage ? customQrImage : autoGeneratedQrUrl;

  // Handle Custom QR Code Image Upload
  const handleCustomQrUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!file.type.startsWith('image/')) {
      alert('Please upload a valid image file (PNG, JPG, WEBP).');
      return;
    }

    if (file.size > 3 * 1024 * 1024) {
      alert('Image size exceeds 3MB limit. Please upload a smaller image.');
      return;
    }

    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result as string;
      setCustomQrImage(result);
      setQrMode('CUSTOM');
      setSaveStatus('IDLE');
    };
    reader.readAsDataURL(file);
  };

  const handleRemoveCustomQr = () => {
    setCustomQrImage('');
    setQrMode('AUTO');
    if (fileInputRef.current) fileInputRef.current.value = '';
    setSaveStatus('IDLE');
  };

  // Perform Save Action
  const executeSave = async () => {
    if (!isVpaValid) {
      setSaveStatus('ERROR');
      setErrorMessage('Please enter a valid UPI ID (e.g. marudhar@oksbi).');
      return;
    }

    if (!merchantName.trim()) {
      setSaveStatus('ERROR');
      setErrorMessage('Please enter your Business / Store Name.');
      return;
    }

    setIsSaving(true);
    setSaveStatus('SAVING');
    setErrorMessage(null);

    const updatedSettings: Partial<PaymentSettings> = {
      upiId: cleanAndSanitizeUPIId(upiId),
      merchantName: merchantName.trim(),
      upiName: merchantName.trim(),
      paymentEnabled,
      paymentInstructions: paymentInstructions.trim(),
      minOrderAmount: Math.max(0, Number(minOrderAmount) || 0),
      maxOrderAmount: Math.max(0, Number(maxOrderAmount) || 0),
      qrCodeCustomImage: qrMode === 'CUSTOM' ? customQrImage : '',
      qrCodeUrl: autoGeneratedQrUrl,
      enableUPI: true,
      enableQR: true,
      gatewayProvider: 'DIRECT_UPI_QR',
    };

    try {
      const startTime = Date.now();
      const success = await updatePaymentSettings(updatedSettings);

      // Ensure slight natural feel (min 300ms) but ultra fast
      const elapsed = Date.now() - startTime;
      if (elapsed < 300) {
        await new Promise((res) => setTimeout(res, 300 - elapsed));
      }

      if (success) {
        setIsSaving(false);
        setSaveStatus('SUCCESS');
        setTimeout(() => {
          setSaveStatus((prev) => (prev === 'SUCCESS' ? 'IDLE' : prev));
        }, 4000);
      } else {
        setIsSaving(false);
        setSaveStatus('ERROR');
        setErrorMessage('Failed to save payment settings to database. Please try again.');
      }
    } catch (err: any) {
      console.error('Save error:', err);
      setIsSaving(false);
      setSaveStatus('ERROR');
      setErrorMessage(err.message || 'An unexpected error occurred while saving.');
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    executeSave();
  };

  const handleCopyUPI = () => {
    navigator.clipboard.writeText(upiId);
    setCopiedUPI(true);
    setTimeout(() => setCopiedUPI(false), 2000);
  };

  return (
    <div className="space-y-6 text-xs max-w-7xl mx-auto">
      
      {/* Top Header & Status Toolbar */}
      <div className="bg-white p-5 rounded-2xl border border-neutral-200/80 shadow-sm flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-emerald-100 text-[#0B8F63] flex items-center justify-center shrink-0 shadow-inner">
            <QrCode className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="font-serif-heading font-bold text-base text-neutral-900">
                Online Payment & UPI Configuration
              </h2>
              {paymentEnabled ? (
                <span className="px-2.5 py-0.5 rounded-full bg-emerald-100 text-emerald-800 text-[10px] font-extrabold uppercase tracking-wider flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-600 animate-pulse" />
                  Active
                </span>
              ) : (
                <span className="px-2.5 py-0.5 rounded-full bg-amber-100 text-amber-800 text-[10px] font-extrabold uppercase tracking-wider">
                  Paused
                </span>
              )}
            </div>
            <p className="text-neutral-500 text-[11px] mt-0.5">
              Manage instant UPI payments, merchant VPA, automatic QR code generation, and customer checkout instructions.
            </p>
          </div>
        </div>

        {/* Action Button */}
        <div className="flex items-center gap-3 self-end sm:self-auto">
          <button
            type="button"
            onClick={executeSave}
            disabled={isSaving}
            className="px-6 py-3 bg-[#0B8F63] hover:bg-[#086F4C] text-white rounded-xl font-extrabold text-xs shadow-md hover:shadow-lg flex items-center gap-2 transition-all disabled:opacity-60 disabled:cursor-not-allowed shrink-0"
          >
            {isSaving ? (
              <>
                <RefreshCw className="w-4 h-4 animate-spin text-white" />
                <span>Saving payment settings...</span>
              </>
            ) : (
              <>
                <Save className="w-4 h-4" />
                <span>Save Payment Settings</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Save Status Banners */}
      {saveStatus === 'SAVING' && (
        <div className="p-4 rounded-2xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-semibold flex items-center gap-3 animate-in fade-in duration-200 shadow-sm">
          <RefreshCw className="w-4 h-4 text-[#0B8F63] animate-spin shrink-0" />
          <span>Saving payment settings to Firebase Firestore database... Please wait.</span>
        </div>
      )}

      {saveStatus === 'SUCCESS' && (
        <div className="p-4 rounded-2xl bg-emerald-100 border border-emerald-300 text-emerald-900 text-xs font-bold flex items-center gap-3 animate-in fade-in duration-200 shadow-sm">
          <CheckCircle2 className="w-5 h-5 text-[#0B8F63] shrink-0" />
          <span>✓ Payment settings updated successfully. Your website is now live with the latest UPI configuration.</span>
        </div>
      )}

      {saveStatus === 'ERROR' && (
        <div className="p-4 rounded-2xl bg-rose-50 border border-rose-200 text-rose-800 text-xs font-semibold flex items-center justify-between gap-3 animate-in fade-in duration-200 shadow-sm">
          <div className="flex items-center gap-2.5">
            <AlertCircle className="w-5 h-5 text-rose-600 shrink-0" />
            <span>{errorMessage || 'Failed to save settings. Please try again.'}</span>
          </div>
          <button
            type="button"
            onClick={executeSave}
            className="px-3.5 py-1.5 bg-rose-600 hover:bg-rose-700 text-white rounded-xl font-bold text-xs flex items-center gap-1.5 transition-colors shrink-0 shadow-sm"
          >
            <RotateCcw className="w-3.5 h-3.5" />
            <span>Retry</span>
          </button>
        </div>
      )}

      {/* Main Settings Form Grid */}
      <form onSubmit={handleSubmit} className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Left 2 Columns: Core UPI Settings */}
        <div className="lg:col-span-2 space-y-6">
          
          {/* Section 1: Online Payment Master Switch */}
          <div className="p-5 bg-white rounded-2xl border border-neutral-200/80 shadow-sm space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-neutral-100">
              <div className="flex items-center gap-2.5">
                <Smartphone className="w-4 h-4 text-[#0B8F63]" />
                <h3 className="font-bold text-neutral-900 text-xs uppercase tracking-wider">
                  Payment Status
                </h3>
              </div>
              <button
                type="button"
                onClick={() => {
                  setPaymentEnabled(!paymentEnabled);
                  setSaveStatus('IDLE');
                }}
                className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors focus:outline-none ${
                  paymentEnabled ? 'bg-[#0B8F63]' : 'bg-neutral-300'
                }`}
              >
                <span
                  className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                    paymentEnabled ? 'translate-x-6' : 'translate-x-1'
                  }`}
                />
              </button>
            </div>

            <div className="flex items-start gap-3">
              <div className="p-2 rounded-xl bg-neutral-100 text-neutral-600 shrink-0 mt-0.5">
                <Info className="w-4 h-4" />
              </div>
              <div>
                <p className="font-bold text-neutral-900 text-xs">
                  {paymentEnabled ? 'Online UPI Payments Enabled' : 'Online UPI Payments Paused'}
                </p>
                <p className="text-neutral-500 text-[11px] mt-0.5 leading-relaxed">
                  {paymentEnabled
                    ? 'Customers can scan QR code or pay via GPay, PhonePe, Paytm, and BHIM during checkout.'
                    : 'Online payment options will be hidden on checkout until re-enabled.'}
                </p>
              </div>
            </div>
          </div>

          {/* Section 2: UPI ID & Business Details */}
          <div className="p-5 bg-white rounded-2xl border border-neutral-200/80 shadow-sm space-y-4">
            <h3 className="font-bold text-neutral-900 text-xs uppercase tracking-wider border-b border-neutral-100 pb-2.5 flex items-center justify-between">
              <span>UPI Credentials & Business Name</span>
              <span className="text-[10px] text-neutral-400 font-normal lowercase">Required for manual UPI payments</span>
            </h3>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              
              {/* UPI ID Input */}
              <div className="space-y-1.5">
                <div className="flex items-center justify-between">
                  <label className="text-xs font-bold text-neutral-800 flex items-center gap-1.5">
                    <span>UPI ID (VPA) *</span>
                  </label>
                  {isVpaValid ? (
                    <span className="text-[10px] font-bold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-full flex items-center gap-1">
                      <Check className="w-3 h-3 text-[#0B8F63]" />
                      Valid UPI VPA
                    </span>
                  ) : upiId.trim().length > 0 ? (
                    <span className="text-[10px] font-bold text-rose-600 bg-rose-50 px-2 py-0.5 rounded-full">
                      Invalid Format (e.g. name@bank)
                    </span>
                  ) : null}
                </div>
                <div className="relative flex items-center">
                  <input
                    type="text"
                    required
                    value={upiId}
                    onChange={(e) => {
                      setUpiId(e.target.value);
                      setSaveStatus('IDLE');
                    }}
                    placeholder="e.g. marudhar@oksbi"
                    className="w-full bg-emerald-50/40 border border-emerald-300/80 rounded-xl py-3 px-3.5 font-mono font-bold text-emerald-950 focus:ring-2 focus:ring-[#0B8F63] focus:bg-white outline-none text-xs transition-all"
                  />
                </div>
                <p className="text-[11px] text-neutral-500">
                  Example: <code className="bg-neutral-100 px-1.5 py-0.5 rounded font-mono text-neutral-800 font-bold">marudhar@oksbi</code> or <code className="bg-neutral-100 px-1.5 py-0.5 rounded font-mono text-neutral-800 font-bold">98290XXXXX@ybl</code>
                </p>
              </div>

              {/* Business Name Input */}
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-neutral-800 block">
                  Business / Store Display Name *
                </label>
                <div className="relative flex items-center">
                  <Building2 className="absolute left-3.5 w-4 h-4 text-neutral-400" />
                  <input
                    type="text"
                    required
                    value={merchantName}
                    onChange={(e) => {
                      setMerchantName(e.target.value);
                      setSaveStatus('IDLE');
                    }}
                    placeholder="Marudhar Fashion Point"
                    className="w-full bg-white border border-neutral-200 rounded-xl py-3 pl-10 pr-3.5 font-semibold text-neutral-900 focus:ring-2 focus:ring-[#0B8F63] outline-none text-xs"
                  />
                </div>
                <p className="text-[11px] text-neutral-500">
                  Displayed on the customer's UPI app payment screen.
                </p>
              </div>

            </div>
          </div>

          {/* Section 3: QR Code Configuration (Auto vs Custom) */}
          <div className="p-5 bg-white rounded-2xl border border-neutral-200/80 shadow-sm space-y-4">
            <div className="flex items-center justify-between border-b border-neutral-100 pb-2.5">
              <h3 className="font-bold text-neutral-900 text-xs uppercase tracking-wider flex items-center gap-2">
                <QrCode className="w-4 h-4 text-[#0B8F63]" />
                <span>UPI QR Code Generation</span>
              </h3>
              <span className="text-[10px] text-neutral-500 font-medium">Automatic or Custom Upload</span>
            </div>

            {/* Mode Tabs */}
            <div className="grid grid-cols-2 gap-3 text-xs">
              <button
                type="button"
                onClick={() => {
                  setQrMode('AUTO');
                  setSaveStatus('IDLE');
                }}
                className={`p-3.5 rounded-xl border font-bold flex items-center justify-center gap-2 transition-all ${
                  qrMode === 'AUTO'
                    ? 'border-[#0B8F63] bg-emerald-50/80 text-[#0B8F63] shadow-sm'
                    : 'border-neutral-200 hover:bg-neutral-50 text-neutral-600'
                }`}
              >
                <Sparkles className="w-4 h-4" />
                <span>Auto-Generate Dynamic QR</span>
              </button>

              <button
                type="button"
                onClick={() => {
                  setQrMode('CUSTOM');
                  setSaveStatus('IDLE');
                }}
                className={`p-3.5 rounded-xl border font-bold flex items-center justify-center gap-2 transition-all ${
                  qrMode === 'CUSTOM'
                    ? 'border-[#0B8F63] bg-emerald-50/80 text-[#0B8F63] shadow-sm'
                    : 'border-neutral-200 hover:bg-neutral-50 text-neutral-600'
                }`}
              >
                <Upload className="w-4 h-4" />
                <span>Upload Custom QR Image</span>
              </button>
            </div>

            {/* Auto Mode Info */}
            {qrMode === 'AUTO' && (
              <div className="p-3.5 bg-neutral-50 rounded-xl border border-neutral-200/80 text-neutral-700 text-xs flex items-start gap-2.5">
                <Sparkles className="w-4 h-4 text-[#0B8F63] shrink-0 mt-0.5" />
                <p className="leading-relaxed">
                  <strong>Automatic QR Code active:</strong> The QR code automatically regenerates whenever you update your UPI ID or Business Name. Customers scan it directly on checkout with 100% accuracy.
                </p>
              </div>
            )}

            {/* Custom Upload Box */}
            {qrMode === 'CUSTOM' && (
              <div className="space-y-3 pt-1">
                <div className="border-2 border-dashed border-neutral-300 rounded-2xl p-4 text-center hover:border-[#0B8F63] transition-colors bg-neutral-50/50">
                  {customQrImage ? (
                    <div className="space-y-3">
                      <img
                        src={customQrImage}
                        alt="Custom Uploaded QR"
                        className="w-36 h-36 mx-auto object-contain rounded-xl border border-neutral-200 bg-white p-2 shadow-md"
                      />
                      <div className="flex items-center justify-center gap-2">
                        <button
                          type="button"
                          onClick={() => fileInputRef.current?.click()}
                          className="px-3 py-1.5 bg-neutral-200 hover:bg-neutral-300 text-neutral-800 rounded-lg text-xs font-bold transition-colors"
                        >
                          Change Image
                        </button>
                        <button
                          type="button"
                          onClick={handleRemoveCustomQr}
                          className="px-3 py-1.5 bg-rose-100 hover:bg-rose-200 text-rose-700 rounded-lg text-xs font-bold flex items-center gap-1 transition-colors"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                          <span>Remove</span>
                        </button>
                      </div>
                    </div>
                  ) : (
                    <div
                      onClick={() => fileInputRef.current?.click()}
                      className="cursor-pointer space-y-2 py-3"
                    >
                      <div className="w-10 h-10 rounded-full bg-emerald-100 text-[#0B8F63] flex items-center justify-center mx-auto">
                        <Upload className="w-5 h-5" />
                      </div>
                      <p className="font-bold text-neutral-800 text-xs">
                        Click or drag custom QR image to upload
                      </p>
                      <p className="text-[11px] text-neutral-500">
                        PNG, JPG, or WEBP (Max 3MB)
                      </p>
                    </div>
                  )}
                  <input
                    ref={fileInputRef}
                    type="file"
                    accept="image/*"
                    onChange={handleCustomQrUpload}
                    className="hidden"
                  />
                </div>
              </div>
            )}
          </div>

          {/* Section 4: Payment Instructions & Limits */}
          <div className="p-5 bg-white rounded-2xl border border-neutral-200/80 shadow-sm space-y-4">
            <h3 className="font-bold text-neutral-900 text-xs uppercase tracking-wider border-b border-neutral-100 pb-2.5 flex items-center gap-2">
              <FileText className="w-4 h-4 text-[#0B8F63]" />
              <span>Checkout Instructions & Order Limits</span>
            </h3>

            {/* Instructions textarea */}
            <div className="space-y-1.5">
              <label className="text-xs font-bold text-neutral-800 block">
                Payment Instructions for Customer
              </label>
              <textarea
                rows={3}
                value={paymentInstructions}
                onChange={(e) => {
                  setPaymentInstructions(e.target.value);
                  setSaveStatus('IDLE');
                }}
                placeholder="Scan the QR code using Google Pay, PhonePe, Paytm, or BHIM UPI app..."
                className="w-full bg-white border border-neutral-200 rounded-xl p-3 text-xs font-medium text-neutral-900 focus:ring-2 focus:ring-[#0B8F63] outline-none leading-relaxed"
              />
              <p className="text-[11px] text-neutral-500">
                Shown to customers during checkout under the QR code image.
              </p>
            </div>

            {/* Min / Max limits */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-neutral-800 block">
                  Minimum Order Amount (₹)
                </label>
                <div className="relative flex items-center">
                  <span className="absolute left-3.5 text-neutral-400 font-bold">₹</span>
                  <input
                    type="number"
                    min={0}
                    value={minOrderAmount}
                    onChange={(e) => {
                      setMinOrderAmount(parseFloat(e.target.value) || 0);
                      setSaveStatus('IDLE');
                    }}
                    placeholder="1"
                    className="w-full bg-white border border-neutral-200 rounded-xl py-2.5 pl-8 pr-3.5 font-bold text-neutral-900 focus:ring-2 focus:ring-[#0B8F63] outline-none text-xs"
                  />
                </div>
              </div>

              <div className="space-y-1.5">
                <label className="text-xs font-bold text-neutral-800 block">
                  Maximum Order Amount (₹) <span className="text-[10px] text-neutral-400 font-normal">(0 = Unlimited)</span>
                </label>
                <div className="relative flex items-center">
                  <span className="absolute left-3.5 text-neutral-400 font-bold">₹</span>
                  <input
                    type="number"
                    min={0}
                    value={maxOrderAmount}
                    onChange={(e) => {
                      setMaxOrderAmount(parseFloat(e.target.value) || 0);
                      setSaveStatus('IDLE');
                    }}
                    placeholder="0"
                    className="w-full bg-white border border-neutral-200 rounded-xl py-2.5 pl-8 pr-3.5 font-bold text-neutral-900 focus:ring-2 focus:ring-[#0B8F63] outline-none text-xs"
                  />
                </div>
              </div>
            </div>
          </div>

        </div>

        {/* Right Column: Live Dynamic QR Preview Card */}
        <div className="space-y-4">
          <div className="p-5 bg-gradient-to-b from-neutral-900 via-neutral-950 to-neutral-900 rounded-2xl text-white shadow-xl space-y-4 sticky top-4 border border-neutral-800">
            
            <div className="flex items-center justify-between text-emerald-400 font-serif-heading font-bold text-sm border-b border-neutral-800 pb-3">
              <div className="flex items-center gap-2">
                <QrCode className="w-5 h-5 text-[#0B8F63]" />
                <span>Live Dynamic QR Preview</span>
              </div>
              <span className="text-[10px] font-mono text-emerald-300 bg-emerald-950 px-2 py-0.5 rounded border border-emerald-800/80">
                REALTIME
              </span>
            </div>

            <p className="text-neutral-300 text-[11px] leading-relaxed">
              This is how your UPI QR Code and business name will render automatically during customer checkout:
            </p>

            {/* QR Card Frame */}
            <div className="bg-white p-4 rounded-2xl text-neutral-900 text-center shadow-2xl border border-neutral-200 space-y-2">
              <div className="relative inline-block">
                <img
                  src={effectiveQrImage}
                  alt="Dynamic UPI QR Code Preview"
                  className="w-48 h-48 mx-auto object-contain rounded-xl bg-white p-1 border border-neutral-100"
                />
                {qrMode === 'CUSTOM' && (
                  <span className="absolute top-2 right-2 bg-emerald-700 text-white text-[9px] font-extrabold px-1.5 py-0.5 rounded shadow">
                    CUSTOM
                  </span>
                )}
              </div>

              <div>
                <p className="font-extrabold text-sm text-neutral-900">{merchantName || 'Marudhar Fashion Point'}</p>
                <p className="font-mono text-xs text-[#0B8F63] font-bold mt-0.5">{upiId || 'marudharfashion@upi'}</p>
              </div>

              <div className="pt-2 border-t border-neutral-100">
                <button
                  type="button"
                  onClick={handleCopyUPI}
                  className="w-full py-2 bg-emerald-50 hover:bg-emerald-100 text-[#0B8F63] rounded-xl font-bold text-xs flex items-center justify-center gap-1.5 transition-colors"
                >
                  {copiedUPI ? <Check className="w-3.5 h-3.5 text-[#0B8F63]" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedUPI ? 'VPA Copied!' : 'Copy UPI VPA'}</span>
                </button>
              </div>
            </div>

            {/* Sample Order Calculation */}
            <div className="p-3.5 bg-neutral-800/80 rounded-xl space-y-2 text-[11px] text-neutral-300 border border-neutral-700/60">
              <div className="flex justify-between">
                <span>Sample Order ID:</span>
                <span className="font-mono font-bold text-white">#MFP1025</span>
              </div>
              <div className="flex justify-between">
                <span>Sample Amount:</span>
                <span className="font-mono font-bold text-emerald-400">₹2,499.00</span>
              </div>
              <div className="flex justify-between">
                <span>Status:</span>
                <span className="font-bold text-emerald-400">
                  {paymentEnabled ? 'Ready for Checkout' : 'Payments Paused'}
                </span>
              </div>
            </div>

            <div className="text-[10px] text-neutral-400 text-center font-medium leading-relaxed italic">
              ⚡ Changes saved here sync instantly across all devices and checkout sessions via Firebase.
            </div>

          </div>
        </div>

      </form>
    </div>
  );
};
